Squashed commit of the following:
commit f13aad9ee36bfba5924d1f6533cdb459566998a1
Merge: f6baa63 ac68d03
Author: Lunga Baliwe <lunga001@gmail.com>
Date:   Thu Oct 6 09:39:52 2022 +0200

    Merge branch '1.x' of github.com:senaite/senaite.queue into 1.x

commit ac68d0308458c1e9e74188e1d319c6f683cb4705
Author: Jordi Puiggené <jp@naralabs.com>
Date:   Fri Jul 1 13:02:41 2022 +0200

    Filter client's cached ghosts tasks when using get_tasks

commit f2eadd6d9e8aa774f4c28a684590100a7aa85d12
Author: Jordi Puiggené <jp@naralabs.com>
Date:   Fri Jul 1 13:01:18 2022 +0200

    Store underlying error in errored tasks

commit 840400d6cf60760893ba7fab99274642831df722
Author: Jordi Puiggené <jp@naralabs.com>
Date:   Sun Apr 3 10:37:03 2022 +0200

    Fix traceback on tasks for the reindex of objects security (#15)

    * Fix traceback on reindex object security

    Queue task for the reindex of object security indexes keep failing
    because of no ceiling when walking up to find nodes:

    ```
    Traceback (innermost last):
      Module ZPublisher.Publish, line 138, in publish
      Module ZPublisher.mapply, line 77, in mapply
      Module ZPublisher.Publish, line 48, in call_object
      Module bika.lims.browser.contact, line 62, in __call__
      Module bika.lims.browser.contact, line 186, in _link_user
      Module bika.lims.content.contact, line 143, in setUser
      [...]
      Module senaite.queue.api, line 294, in add_reindex_obj_security_task
      Module senaite.queue.api, line 274, in walk_up
      Module senaite.queue.api, line 274, in walk_up
      Module senaite.queue.api, line 270, in walk_up
      Module senaite.queue.api, line 245, in walk_down
      Module bika.lims.api, line 429, in get_uid
      Module bika.lims.api, line 239, in get_object
      Module bika.lims.api, line 202, in fail
    APIError: <AuditLogCatalog at /senaite/auditlog_catalog> is not supported.
    ```

    * Changelog

commit 196d0725ee1d929c80f8eccc53cd613150526ce9
Author: Jordi Puiggené <jp@naralabs.com>
Date:   Wed Oct 20 11:33:29 2021 +0200

    Use intial task's default chunk size when creating subsequent tasks (#14)

commit f6baa636988561015a9991fd32eaaa3dac7cb358
Author: Lunga Baliwe <lunga001@gmail.com>
Date:   Thu Sep 23 14:59:34 2021 +0200

    Get sample uid from analysis by getting analysis object when creating a
    worksheet from a worksheet template

commit e6995f78490137d61699e91989c9f5813f34347f
Author: Lunga Baliwe <lunga001@gmail.com>
Date:   Thu Aug 5 20:15:11 2021 +0200

    Change minor imports for senaite core v2 and unpin "senaite.lims<1.4.0"